@startuml
'https://plantuml.com/class-diagram

class TranslateToDutch {
- koenenDictionary : KoenenDictionary
- kramersDictionary : KramersDictionary
+ getKoenenDictionary() : KoenenDictionary
+ getKramersDictionary() : KramersDictionary
}

class KoenenDictionary {
- words : Hashtable
+ openEnglishDutch() : void
+ openDutchEnglish() : void
+ lookUp(woord : String) : String
}

class KramersDictionary {
- list : String[][]
+ find(woord : String) : String
}



@enduml